FROM python:3
WORKDIR /app
COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh
COPY requirements.txt .
RUN pip install -r requirements.txt
CMD ["python3", "app.py"]
# CMD ["./wait-for-it.sh", "messaging-rabbitmq-1:5672", "-s", "--", "python3", "app.py"]
